# make dic of games and their WR's

facts = ["The common cold is a type of virus.","Moulds, yeasts and mushrooms are types of fungus.",
         "The founder of match.com, Gary Kremen, lost his girlfriend to a man she met on match.com.",
         "A pumping human heart can squirt blood 30ft.",
         "The shortest war ever fought was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
         "Liechtenstein, the world’s sixth smallest country, is the largest exporter of false teeth.",
         "Finland has the highest density of metal bands in the world.",
         "“Twitter” was a 19th-century word for an abscess on a horse’s foot.",
         "Scallops have up to 100 eyes.",
         "Forest fires can be sparked by sunlight magnified by water on dried-out leaves.",
         "You are more likely to believe a statement that is printed in bold.",
         "Areas of the Moon include the Ocean of Storms, the Marsh of Decay and the Lake of Death.",
         "A baby echidna is called a ‘puggle’.",
         "In 1568, the Catholic Church condemned the entire population of the Netherlands to death for heresy.",
         "Bacteria and amoebas are far more different from each other than amoebas are from people.",
         "90% of all jellyfish are smaller than a human thumbnail.",
         "Photographs of Algae, published in 1845, was the first book ever to contain photographs.",
         "Vultures can turn a dead body into a skeleton in under five hours.",
         "In 2006, the most popular name for cows in Switzerland was Fiona.",
         "Switzerland monitors its airspace around the clock but only intercepts illegal flights during office hours.",
         "The first book ever printed in Oxford had a misprint on the first page: they got the date wrong.",
         "Everybody expected the Spanish Inquisition – they were legally obliged to give 30 days’ notice.",
         "The Ancient Greeks claimed the sky was bronze as they had no word for blue.",
         "The average human body carries ten times more bacterial cells than human cells.",
         "It can take a photon 40,000 years to travel from the core of the sun to its surface, but only 8 minutes to travel the rest of the way to Earth.",
         "There are 8 times as many atoms in a teaspoonful of water as there are teaspoonfuls of water in the Atlantic ocean.",
         "If you could drive your car straight up you would arrive in space in just over an hour.",
         "The dinosaurs became extinct before the Rockies or the Alps were formed.",
         "The Australian billygoat plum contains 100 times more vitamin C than an orange.",
         "An electric eel can produce a shock of up to 650 volts.",
         "Without its lining of mucus your stomach would digest itself.",
         "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
         "Humans have 46 chromosomes, peas have 14 and crayfish have 200.",
         "Utopia ia a large, smooth lying area of Mars.",
         "The low frequency call of the humpback whale is the loudest noise made by a living creature.",
         "Somewhere in the flicker of a badly tuned TV set is the background radiation from the Big Bang.",
         "The risk of being struck by a falling meteorite for a human is one occurence every 9,300 years.",
         "India’s Dahala Khagrabari is the world’s only third-order enclave.",
         "The light emitted by 200,000 galaxies makes our universe a shade of beige.",
         "If you open your eyes in a pitch-black room, the color you’ll see is called eigengrau.",
         "According to an analysis by FiveThirtyEight, 44 percent of Bob Ross's paintings contain at least one 'happy little cloud'",
         "Sea cucumbers eat with their feet.",
         "The archerfish knocks its insect prey out of over-hanging branches with a stream of spit.",
         "Marie Curie's notebooks are still radioactive. Researchers hoping to view them must sign a disclaimer.",
         "The first webcam watched a coffee pot. It allowed researchers at Cambridge to monitor the coffee situation without leaving their desks.",
         "In Super Mario Bros., the bushes are just clouds colored green.",
         "When fruit flies are infected with a parasite, they self-medicate with booze—they seek out food with higher alcohol content.",
         "On Good Friday in 1930, the BBC reported, 'There is no news'. Instead, they played piano music.",
         "About one in every 4 million lobsters is born with a rare genetic defect that turns it blue.",
         "The Icelandic phone book is ordered by first name.",
         "Before fridges were invented, Russians and Finns kept their milk fresh by putting live frogs in it.",
         "Hamsters can store half their own weight in food in their cheeks.",
         "The smallest trees in the world are the dwarf willows of Greenland. They are two inches tall.",
         "Toasters were banned in Havana until 2008.",
         "The so-called “Wicked Bible” published in 1631 contained the typo, “Thou shalt commit adultery.”",
         "Banging your head against a wall burns 150 calories an hour.",
         "Movie trailers were originally shown after the movie, which is why they were called “trailers”.",
         "The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
         "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
         "Catfish are the only animals that naturally have an odd number of whiskers.",
         "The French language has seventeen different words for ‘surrender’.",
         "Slugs have 4 noses.",
         "Pirates wore earrings because they believed it improved their eyesight.",
         "It snowed in the Sahara desert for 30 minutes on the 18th February 1979.",
         "The most venomous jellyfish in the world is named the Irukandji and is smaller than your fingernail."]

game_wr = {"Syberia": "Syberia WR is 2:00:16 by Nicko!",
           "Syberia 2": "Syberia II WR is 1h 27m 13s by Bigmanjapan",
           "Total Overdose": "Total Overdose WR is 55m 24s by NoCredit",
           "Child of Light": "Child of Light WR is 1h 14m 44s by takaze",
           "Year Walk": "Year Walk WR is 13m 53s by eigenbasis",
           "Runner2": "Bit.Trip Presents... Runner2: Future Legend of Rhythm Alien WR is 1h 47m 19s by eigenbasis",
           "GTA: SA": "Grand Theft Auto: San Andreas WR is 4h 22m 19s by lelreset"}

bad_words = []

with open("bad_words.txt") as f:
    bad_words = f.read().splitlines()
