# make dic of games and their WR's

facts = ["The common cold is a type of virus.","Moulds, yeasts and mushrooms are types of fungus.",
         "The founder of match.com, Gary Kremen, lost his girlfriend to a man she met on match.com.",
         "A pumping human heart can squirt blood 30ft.",
         "The shortest war ever fought was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
         "Liechtenstein, the world’s sixth smallest country, is the largest exporter of false teeth.",
         "Finland has the highest density of metal bands in the world.",
         "“Twitter” was a 19th-century word for an abscess on a horse’s foot.",
         "Scallops have up to 100 eyes.",
         "Forest fires can be sparked by sunlight magnified by water on dried-out leaves.",
         "You are more likely to believe a statement that is printed in bold.",
         "Areas of the Moon include the Ocean of Storms, the Marsh of Decay and the Lake of Death.",
         "A baby echidna is called a ‘puggle’.",
         "In 1568, the Catholic Church condemned the entire population of the Netherlands to death for heresy.",
         "Bacteria and amoebas are far more different from each other than amoebas are from people.",
         "90% of all jellyfish are smaller than a human thumbnail.",
         "Photographs of Algae, published in 1845, was the first book ever to contain photographs.",
         "Vultures can turn a dead body into a skeleton in under five hours.",
         "In 2006, the most popular name for cows in Switzerland was Fiona.",
         "Switzerland monitors its airspace around the clock but only intercepts illegal flights during office hours.",
         "The first book ever printed in Oxford had a misprint on the first page: they got the date wrong.",
         "Everybody expected the Spanish Inquisition – they were legally obliged to give 30 days’ notice.",
         "The Ancient Greeks claimed the sky was bronze as they had no word for blue.",
         "The average human body carries ten times more bacterial cells than human cells.",
         "It can take a photon 40,000 years to travel from the core of the sun to its surface, but only 8 minutes to travel the rest of the way to Earth.",
         "There are 8 times as many atoms in a teaspoonful of water as there are teaspoonfuls of water in the Atlantic ocean.",
         "If you could drive your car straight up you would arrive in space in just over an hour.",
         "The dinosaurs became extinct before the Rockies or the Alps were formed.",
         "The Australian billygoat plum contains 100 times more vitamin C than an orange.",
         "An electric eel can produce a shock of up to 650 volts.",
         "Without its lining of mucus your stomach would digest itself.",
         "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
         "Humans have 46 chromosomes, peas have 14 and crayfish have 200.",
         "Utopia ia a large, smooth lying area of Mars.",
         "The low frequency call of the humpback whale is the loudest noise made by a living creature.",
         "Somewhere in the flicker of a badly tuned TV set is the background radiation from the Big Bang.",
         "The risk of being struck by a falling meteorite for a human is one occurence every 9,300 years.",
         "India’s Dahala Khagrabari is the world’s only third-order enclave.",
         "The light emitted by 200,000 galaxies makes our universe a shade of beige.",
         "If you open your eyes in a pitch-black room, the color you’ll see is called eigengrau.",
         "According to an analysis by FiveThirtyEight, 44 percent of Bob Ross's paintings contain at least one 'happy little cloud'",
         "Sea cucumbers eat with their feet.",
         "The archerfish knocks its insect prey out of over-hanging branches with a stream of spit.",
         "Marie Curie's notebooks are still radioactive. Researchers hoping to view them must sign a disclaimer.",
         "The first webcam watched a coffee pot. It allowed researchers at Cambridge to monitor the coffee situation without leaving their desks.",
         "In Super Mario Bros., the bushes are just clouds colored green.",
         "When fruit flies are infected with a parasite, they self-medicate with booze—they seek out food with higher alcohol content.",
         "On Good Friday in 1930, the BBC reported, 'There is no news'. Instead, they played piano music.",
         "About one in every 4 million lobsters is born with a rare genetic defect that turns it blue."]
